### ISSUE TITLE
[feature request] Display size freed  up by emptying 

### ISSUE THREAD

**Issue by Whoaa512** [sindresorhus/empty-trash-cli#3]
Either a before/after log similar to [node-prune](https://github.com/tj/node-prune) 

Or just a simple `XX Gb freed`

**Comment by sindresorhus** [comment]
That's an interesting suggestion, but not something I would use or want in this package. However, you could build your own CLI that uses `empty-trash` underneath and provide nicer output. I'm happy to link to it in the readme if you decide to make that.
