### ISSUE TITLE
Doesn't seem to work on Big Sur 11.2.2

### ISSUE THREAD

**Issue by JayBrown** [sindresorhus/empty-trash-cli#5]
I tried `empty-trash` on macOS 11.2.2, but it only launched Finder, but then did nothing.

When I run the following command, it works fine:

`osascript -e 'tell application "Finder"' -e 'activate' -e 'delay 0.5' -e 'empty trash' -e 'end tell'`

Note: I have disabled Finder (i.e. it's never running), and I only enable when I need it (which is rarely). That's what the `delay 0.5` is for… sometimes Finder launch is too slow, and the `empty trash` part will then fail. Maybe that's also the problem with `empty-trash-cli` in my case?

**Comment by sindresorhus** [comment]
It works fine for me on macOS 11.2.1. It's expected that Finder is running. Disabling Finder is such an obscure thing to do that I'm not even sure it's worth noting it in the readme.

**Comment by JayBrown** [comment]
No problem. I can use my own solution.
